#pragma once

#define REPLACE_INTERFERENCE_WITH_SUMMARY true
#define USE_MODIFIED_FIXEDPOINT true // only applied in summary-mode
#define SKIP_SUMMARY_OPTIMIZATION true

#define CAS_OVERAPPROXIMATE_AGE_ASSIGNMENT true
#define CAS_OVERAPPROXIMATE_AGE_PROPAGATION true
#define PRF_REALLOCATION true
